config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  get 'login', to:'login#new'  
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'
  post 'message', to: 'messages#create'


  mount ActionCable.server, at:'/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user 
    validates :body, presence:true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    validates :username, uniqueness:true,presence:true, length:{minimum:3,maximum:15}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user
    def index 
        puts("hhhhhh")
        @message = Message.all 
        
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

    before_action :logged_in_redirect, only: [:new, :create]

    def new 
    end

    def create
    puts(params)
    user = User.find_by(username: params[:session][:username].to_s)
    # if(user==nil)
    #   for i in 1..5
    #     puts "hello"
    # end 
    #   puts params[:session][:username].to_s
    # end
    if user && user.authenticate(params[:session][:password].to_s)
        session[:user_id] = user.id
        flash[:success] = "You have successfully logged in"
        redirect_to root_path
    else
        for i in 1..5
            puts "helloaaddd"
        end 
        puts user.u
        flash.now[:error] = "There was something wrong with your login information"
        render 'new'
    end
    end

    def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
    end

    private
    def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user
    
    def create
        message = current_user.messages.build(message_params)
        #if message.save
       
        ActionCable.server.broadcast "chatroom_channel", foo: message.body, name:message.user.username

        #end
    end
    
    private
    
    def message_params
        for i in 1..5 
            puts ""
        end
        puts params
        params.permit(:body)
    end
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular pink coffee icon"></i>
  Say Something
</h4>


<div class="ui two column grid">
<div class="twelve wide column">
<div class="ui fluid raised card chatbox">
  <div class="content" id="messages">
<div class="ui feed" id="pechi">
    <%= render @message %>
</div>
</div>
<div class="extra content">
<%= form_for(:message, html: {class: "ui reply form", role: "form"}, url: message_path) do |f| %>
    
    <div class="field">
       <div class="ui fluid icon input">
       
       <input type="text" name="body" placeholder="Enter a message...">
      <%= f.button '<i class="bordered inverted pink edit icon"></i>'.html_safe %>
    </div> 
    </div>
    
  <% end %>
</div>

</div>
</div>

<div class="four wide column">
<div class="ui fluid raised card chatbox">
  <div class="content">
<div class="ui inverted vertical menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <a class="item">
    Friends
  </a>
  </div></div>
</div>
</div>

</div>

<script>
  scroll_buttom = function() {
          if ($('#messages').length>0){
            $('#messages').scrollTop($('#messages')[0].scrollHeight);
          }
        }
        scroll_buttom();
<script>

app/views/layouts/_nav.html.erb
<div class="ui small inverted menu">
        <div class="ui container"> 
        <a href=<%=root_path%> class="item">
          Chatroom
        </a>
        <a class="item">
          Messages
        </a>
        <div class="right menu">
          <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>
            <div class="menu">
            <% if logged_in? %>
              <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
            <% else %>
              <%= link_to "Log in", login_path, class: "item" %>
            <% end %>
            </div>
          </div>
        <% if !logged_in? %>
          <div class="item">
            <%= link_to "Log in", login_path, class: "ui primary button" %>
          </div>
        <% end %>
          </div>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
      <div class="ui container">
       
        <%= yield %>
      </div>

      <script>
        $('.ui.dropdown')
         .dropdown()
        ;
        $('.message .close').on('click', function() {
        $(this).closest('.message').transition('fade');
        });

        scroll_buttom = function() {
          if ($('#messages').length>0){
            $('#messages').scrollTop($('#messages')[0].scrollHeight);
          }
        }
        scroll_buttom();
      </script>
  </body>
</html>

app/views/login/new.html.erb
<h2 class="ui center aligned medium icon header">
    Welcome To MessageMe - Group Chat APP
</h2>


<h4 class="ui center aligned medium icon header">
  <i class="circular pink sign-in icon"></i>
  Login To Continue
</h4>


<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Login", class: "ui pink submit button" %>
      <% end %>
    </div>
    <div class="middle aligned column">
      <div class="ui pink big button">
        <i class="signup  icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
      <div class="summary">
         <em style="color:#fe019a"><%=message.user.username%></em> :<%=message.body%>
      </div>
    </div>
  </div>